2024-04-03 08:36:03,580 - __main__ - ERROR - Error starting bot: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-04-03 08:48:07,676 - __main__ - ERROR - Failed to start bot: 500 - Error starting bot: module 'flumine.flumine' has no attribute 'streams'
2024-04-03 09:46:46,674 - __main__ - ERROR - Error starting bot: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /start (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efcb0ade050>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-04-03 09:47:59,751 - __main__ - ERROR - Failed to start bot: 400 - Bot is already running or not initialized
2024-04-03 09:48:44,684 - __main__ - ERROR - Failed to start bot: 400 - Bot is already running or not initialized
2024-04-03 10:05:19,976 - __main__ - ERROR - Failed to start bot: 500 - Error starting bot: 'NoneType' object has no attribute 'market_filter'
2024-04-03 10:10:45,370 - __main__ - ERROR - Error starting bot: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-04-03 10:13:55,732 - __main__ - ERROR - Error starting bot: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2024-04-03 11:12:28,752 - __main__ - ERROR - Error starting bot: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
